server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
    
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pixogram?useSSL=false
    username: root
    password: pass@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties: 
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect